[character]
success_symbol = "[▶](bold green)"
error_symbol = "[▶](bold red)"
# success_symbol = "[➜](bold green)"
# error_symbol = "[➜](bold red)"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[nodejs]
symbol = " "

[rust]
symbol = " "

[kubernetes]
format = 'on [$symbol$context \($namespace\)](dimmed yellow) '
disabled = false

[aws]
disabled = false

[gcloud]
disabled = true

[custom.kubie]
command = "echo '[kubie]'"
when = '''kubie info ctx'''

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[$user ]($style)'
